source 'https://rubygems.org'

# IRuby dependencies
gem 'pry'
gem 'pry-doc'
gem 'awesome_print'
gem 'cztop', '< 0.3.0'
gem 'iruby', github: 'sciruby/iruby'

# PyCall related gems
gem 'pycall', github: 'mrkn/pycall'
gem 'matplotlib', github: 'mrkn/matplotlib.rb'
